.PHONY:all
all:
	mkdir -p ../../bin/raw_examples/http_parser
	g++ -std=c++11 http_parser_demo.cpp http_parser.c -o ../../bin/raw_examples/http_parser/http_parser_demo -g -I./

.PHONY:clean
clean:
	rm -rf main